# Generated by Django 2.2 on 2019-04-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('time', models.URLField()),
                ('life_days', models.CharField(max_length=200)),
                ('present_heads_group', models.IntegerField()),
                ('total_dead_heads_group', models.IntegerField()),
                ('Internal_average_temperature', models.DecimalField(decimal_places=1, max_digits=10)),
                ('Internal_humidity', models.IntegerField()),
                ('external_temperature', models.DecimalField(decimal_places=1, max_digits=10)),
                ('external_humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('water_head', models.IntegerField()),
                ('food_head', models.IntegerField()),
            ],
        ),
    ]
