# Generated by Django 2.2 on 2019-05-08 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sunghwan', '0002_auto_20190415_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='입력일자')),
                ('Total_count', models.IntegerField(default=0, verbose_name='전체개수')),
                ('Total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='전체무게')),
                ('Big_king_egg_count', models.IntegerField(default=0, verbose_name='큰왕란개수')),
                ('Big_king_egg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='큰왕란무게')),
                ('King_egg_count', models.IntegerField(default=0, verbose_name='왕란개수')),
                ('King_egg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='왕란무게')),
                ('Special_egg_count', models.IntegerField(default=0, verbose_name='특란개수')),
                ('Special_egg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='특란무게')),
                ('Large_egg_count', models.IntegerField(default=0, verbose_name='대란개수')),
                ('Large_egg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='대란무게')),
                ('Medium_egg_count', models.IntegerField(default=0, verbose_name='중란개수')),
                ('Medium_egg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='중란무게')),
                ('Small_egg_count', models.IntegerField(default=0, verbose_name='소란개수')),
                ('Small_egg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='소란무게')),
                ('Smaller_egg_count', models.IntegerField(default=0, verbose_name='경란개수')),
                ('Smaller_egg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='경란무게')),
                ('Smallest_egg_count', models.IntegerField(default=0, verbose_name='등외란개수')),
                ('Smallest_egg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='등외란무게')),
            ],
        ),
    ]
